#此文件为发送间隔cd配置，0为无间隔
#撤回间隔目前均为不撤回，需要请自行配置
#以下为指令触发间隔，单位毫秒

#b站404随机漫画
comiccd: 0

#mc戳一戳
mcchuoyichuocd: 0

#盲盒
mhcd: 0

#st（清凉图）
ssttoooccd: 0

#stplus(铯图)
seettuupluscd: 0

#三元图
sanciyuancd: 0

#原神盲盒
yuanmangheshencd: 0

#云溪图
yunxiyuancd: 0
