#此配置项为是否开启仅主人生效
#true为仅主人生效，false为所有人可生效
#st(清凉图）
ssttooocmaster: false

#stplus（铯图）
seettuuplusmaster: false

#云溪院随机图
yunxiyuanmaster: false

one: false
two: false
three: false
four: false
five: false
six: false
seven: false
eight: false
nine: false
ten: false
















